version: '2.1'

volumes:
  db:
  redis:
  app:

networks:
  internal:

services:
  db:
    build: docker/db
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
      - .rbenv-vars
    healthcheck:
      test: "CMD echo 'SELECT 1' | PGPASSWORD=password psql --host 127.0.0.1 --username postgres --dbname hyrax_development --quiet --no-align --tuples-only"
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      internal:

  app:
    build: .
    env_file:
      - .env
      - .rbenv-vars
    volumes:
      - /data/box:/box
      - /data/source:/data
      - /data/transfer:/transfer
      - app:/data/tmp/uploads
    networks:
      internal:

  web:
    extends:
      service: app
    command: bash -c "/bin/docker-entrypoint.sh"
    depends_on:
      - db
      - redis
    ports:
      - 3000:3000

  workers:
    extends:
      service: app
    command: bash -c "bundle exec sidekiq"
    environment:
      - SETTINGS__FITS_PATH=/opt/fits-1.0.5/fits.sh
    depends_on:
      - db
      - redis

  redis:
    image: redis:5
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
    expose:
      - 6379
    networks:
      internal:
    healthcheck:
      test: "CMD redis-cli ping"
      interval: 30s
      timeout: 5s
      retries: 3
