---
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
production:
  :concurrency: 1
  :verbose: false
  :pidfile: <%= File.join(ENV.fetch('PIDS_PATH', 'tmp'),'sidekiq.pid') %>
  :logfile: <%= File.join(ENV.fetch('LOGS_PATH','log'), 'sidekiq.log') %>
development:
  :verbose: true
:queues:
  - default
  - crosswalk
  - gush
  - workflow_monitor
